import Head from "next/head";
import {
  Navbar,
  Hero,
  Corecourses,
  Specializedcourse,
  About,
  Team__members,
  Footer,
} from "./component";
import React from "react";
export default function Home() {
  return (
    <>
      <Head>
        <title>panaverse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="favicon.png" type="image/x-icon" />
      </Head>
      <Navbar />
      <Hero />
      <Corecourses />
      <Specializedcourse />
      <About />
      <div className="w-full h-full m-0 p-0 mt-20 bg-gradient-to-r from-secondry-300/10 to-secondry-400/10 rounded-tl-[600px] rounded-tr-[600px]">
        <Team__members />
        <Footer />
      </div>
    </>
  );
}
