import Head from "next/head";
import Navbar from "./component/layout/Navbar";
import Hero from "./component/widgets/Hero";
export default function Home() {
  return (
    <>
      <Head>
        <title>panaverse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="favicon.png" type="image/x-icon" />
      </Head>
      <Navbar />
      <Hero />
    </>
  );
}
